/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vuelouy.interfaz.common;

import vuelouy.dominio.Viaje;
import javax.swing.JPanel;

/**
 *
 * @author alumnoFI
 */
public class InicioTripulante extends javax.swing.JFrame{

    private MenuMensajes menu_Mensaje;
    private MenuListaPedidos menu_Pedidos;
    private MenuConfiguracionTripulante menu_Configuracion;

    private final Viaje viaje;
    private ComunicacionPaneles comunicacion;
    
    /**
     *
     * @param v
     * @param com
     */
    public InicioTripulante(Viaje v, ComunicacionPaneles com) {
        viaje = v;
        comunicacion = com;
        initComponents();
        this.setSize(798, 600);
        this.setLocation(801, 0);
        cargarPaneles();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMensajes = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnConfiguracionPiloto = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        lblLstPedidos = new javax.swing.JLabel();
        lblConfiguracion = new javax.swing.JLabel();
        jLayeredTripulante = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Tripulante");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(116, 578));

        btnMensajes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMensajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Mensaje.png"))); // NOI18N
        btnMensajes.setBorder(null);
        btnMensajes.setBorderPainted(false);
        btnMensajes.setContentAreaFilled(false);
        btnMensajes.setPreferredSize(new java.awt.Dimension(96, 96));
        btnMensajes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/MensajeP.png"))); // NOI18N
        btnMensajes.setRequestFocusEnabled(false);
        btnMensajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensajesActionPerformed(evt);
            }
        });

        btnPedidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Pedidos.png"))); // NOI18N
        btnPedidos.setBorder(null);
        btnPedidos.setBorderPainted(false);
        btnPedidos.setContentAreaFilled(false);
        btnPedidos.setPreferredSize(new java.awt.Dimension(96, 96));
        btnPedidos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/PedidosP.png"))); // NOI18N
        btnPedidos.setRequestFocusEnabled(false);
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        btnConfiguracionPiloto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnConfiguracionPiloto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/configuracionP.png"))); // NOI18N
        btnConfiguracionPiloto.setBorder(null);
        btnConfiguracionPiloto.setBorderPainted(false);
        btnConfiguracionPiloto.setContentAreaFilled(false);
        btnConfiguracionPiloto.setDefaultCapable(false);
        btnConfiguracionPiloto.setPreferredSize(new java.awt.Dimension(96, 96));
        btnConfiguracionPiloto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Configuracion.png"))); // NOI18N
        btnConfiguracionPiloto.setRequestFocusEnabled(false);
        btnConfiguracionPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionPilotoActionPerformed(evt);
            }
        });

        lblMensaje.setBackground(new java.awt.Color(255, 255, 255));
        lblMensaje.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setText("Mensajes");

        lblLstPedidos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblLstPedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLstPedidos.setText("Pedidos");

        lblConfiguracion.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfiguracion.setText("Configuración");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblLstPedidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConfiguracionPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje)
                .addGap(80, 80, 80)
                .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLstPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfiguracionPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConfiguracion)
                .addGap(22, 22, 22))
        );

        jLayeredTripulante.setPreferredSize(new java.awt.Dimension(589, 578));

        javax.swing.GroupLayout jLayeredTripulanteLayout = new javax.swing.GroupLayout(jLayeredTripulante);
        jLayeredTripulante.setLayout(jLayeredTripulanteLayout);
        jLayeredTripulanteLayout.setHorizontalGroup(
            jLayeredTripulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );
        jLayeredTripulanteLayout.setVerticalGroup(
            jLayeredTripulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredTripulante, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredTripulante, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMensajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensajesActionPerformed
        mostrar(menu_Mensaje);
    }//GEN-LAST:event_btnMensajesActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        mostrar(menu_Pedidos);
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnConfiguracionPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionPilotoActionPerformed
        mostrar(menu_Configuracion);
    }//GEN-LAST:event_btnConfiguracionPilotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfiguracionPiloto;
    private javax.swing.JButton btnMensajes;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JLayeredPane jLayeredTripulante;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfiguracion;
    private javax.swing.JLabel lblLstPedidos;
    private javax.swing.JLabel lblMensaje;
    // End of variables declaration//GEN-END:variables

    private void cargarPaneles() {
        menu_Mensaje = new MenuMensajes(comunicacion);
        menu_Pedidos = new MenuListaPedidos(viaje, comunicacion);
        menu_Configuracion = new MenuConfiguracionTripulante(viaje);

        jLayeredTripulante.setSize(589, 578);
        jLayeredTripulante.setVisible(true);

    }

    private void mostrar(JPanel menu) {

        jLayeredTripulante.removeAll();
        menu.setSize(585, 548);
        jLayeredTripulante.add(menu);

        ocultarPaneles();
        menu.setVisible(true);
    }

    private void ocultarPaneles(){
        menu_Mensaje.setVisible(false);
        menu_Pedidos.setVisible(false);
        menu_Configuracion.setVisible(false);
    }
    
    public void notificar(boolean n){
        if (n) {
            btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/PedidosN.png")));
        } else  {
            btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Pedidos.png")));
        }
    }
}
