/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vuelouy.interfaz.common;

import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author alumnoFI
 */
public class MenuMensajes extends javax.swing.JPanel implements Observer{

    /**
     * Creates new form MenuMensajes
     */
    private ComunicacionPaneles comunicacion;
    
    /**
     *
     */
    public MenuMensajes() {
        initComponents();
    }
    
    /**
     *
     * @param p
     */
    public MenuMensajes(ComunicacionPaneles p) {
        comunicacion = p;
        comunicacion.addObserver(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnDespegue = new javax.swing.JButton();
        btnArribando = new javax.swing.JButton();
        btnTurbulencia = new javax.swing.JButton();
        btnBienvenida = new javax.swing.JButton();
        lblDespegando = new javax.swing.JLabel();
        lblArribando = new javax.swing.JLabel();
        lblTurbulencia = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(585, 548));

        btnDespegue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Despegue.png"))); // NOI18N
        btnDespegue.setBorder(null);
        btnDespegue.setBorderPainted(false);
        btnDespegue.setContentAreaFilled(false);
        btnDespegue.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/DespegueP.png"))); // NOI18N
        btnDespegue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespegueActionPerformed(evt);
            }
        });

        btnArribando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Aterrizar.png"))); // NOI18N
        btnArribando.setBorder(null);
        btnArribando.setBorderPainted(false);
        btnArribando.setContentAreaFilled(false);
        btnArribando.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/AterrizarP.png"))); // NOI18N
        btnArribando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArribandoActionPerformed(evt);
            }
        });

        btnTurbulencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Turbulencia.png"))); // NOI18N
        btnTurbulencia.setBorder(null);
        btnTurbulencia.setBorderPainted(false);
        btnTurbulencia.setContentAreaFilled(false);
        btnTurbulencia.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/TurbulenciaP.png"))); // NOI18N
        btnTurbulencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurbulenciaActionPerformed(evt);
            }
        });

        btnBienvenida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Bienvenida.png"))); // NOI18N
        btnBienvenida.setBorder(null);
        btnBienvenida.setBorderPainted(false);
        btnBienvenida.setContentAreaFilled(false);
        btnBienvenida.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/BienvenidaP.png"))); // NOI18N
        btnBienvenida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBienvenidaActionPerformed(evt);
            }
        });

        lblDespegando.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblDespegando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDespegando.setText("Despegando");

        lblArribando.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblArribando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArribando.setText("Arribando");

        lblTurbulencia.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblTurbulencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTurbulencia.setText("Turbulencia");

        lblBienvenida.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("Bienvenida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDespegue, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDespegando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(215, 215, 215)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnArribando, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArribando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTurbulencia, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTurbulencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(btnBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnArribando, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDespegue, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDespegando)
                    .addComponent(lblArribando))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTurbulencia, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTurbulencia)
                    .addComponent(lblBienvenida))
                .addGap(126, 126, 126))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDespegueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespegueActionPerformed
        comunicacion.setbMensaje(true);
        comunicacion.cambio("Despegando");
    }//GEN-LAST:event_btnDespegueActionPerformed

    private void btnArribandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArribandoActionPerformed
        comunicacion.setbMensaje(true);
        comunicacion.cambio("Arribar");
    }//GEN-LAST:event_btnArribandoActionPerformed

    private void btnTurbulenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurbulenciaActionPerformed
        comunicacion.setbMensaje(true);
        comunicacion.cambio("Turbulencia");
    }//GEN-LAST:event_btnTurbulenciaActionPerformed

    private void btnBienvenidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBienvenidaActionPerformed
        comunicacion.setbMensaje(true);
        comunicacion.cambio("Bienvenida");
    }//GEN-LAST:event_btnBienvenidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArribando;
    private javax.swing.JButton btnBienvenida;
    private javax.swing.JButton btnDespegue;
    private javax.swing.JButton btnTurbulencia;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblArribando;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblDespegando;
    private javax.swing.JLabel lblTurbulencia;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        comunicacion.getVentanaInicioP().mostrarSubMenu(comunicacion.getPanel());
    }
}
