/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vuelouy.interfaz.common;

import vuelouy.dominio.TextoHTML;
import java.io.IOException;
import java.net.MalformedURLException;
import javax.swing.text.html.HTMLEditorKit;
import java.net.URL;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alumnoFI
 */
public class MenuRevistas extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form MenuRevistas
     *
     */
    private ComunicacionPaneles comunicacion;
    private TextoHTML textoHtml; 

    /**
     *
     */
    public MenuRevistas() {
        initComponents();
    }

    /**
     *
     * @param p
     */
    public MenuRevistas(ComunicacionPaneles p) {
        comunicacion = p;
        comunicacion.addObserver(this);
        initComponents();
        textoHtml = new TextoHTML();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRevista = new javax.swing.JButton();
        btnLibro = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblLectura = new javax.swing.JLabel();
        lblRevista = new javax.swing.JLabel();
        lblPrincipito = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jepLectura = new javax.swing.JEditorPane();

        setPreferredSize(new java.awt.Dimension(664, 548));

        btnRevista.setRolloverEnabled(false);
        btnRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevistaActionPerformed(evt);
            }
        });

        btnLibro.setRolloverEnabled(false);
        btnLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibroActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Volver.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setPreferredSize(new java.awt.Dimension(96, 96));
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/VolverP.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblLectura.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblLectura.setText("Lectura");

        lblRevista.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblRevista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRevista.setText("Orgullo y Prejuicio");

        lblPrincipito.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblPrincipito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrincipito.setText("El Principito");

        jepLectura.setEditable(false);
        jepLectura.setContentType("text/html"); // NOI18N
        jScrollPane2.setViewportView(jepLectura);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(lblPrincipito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblRevista))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLectura))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLectura)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRevista)
                        .addGap(18, 18, 18)
                        .addComponent(btnLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPrincipito)
                        .addGap(52, 52, 52)))
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevistaActionPerformed
        if (comunicacion.getIdioma().equals("ingles")) {
            jepLectura.setText(textoHtml.getOrgYPreIngles());
        }
        if (comunicacion.getIdioma().equals("español")) {
            jepLectura.setText(textoHtml.getOrgYPreEspañol());
        }
    }//GEN-LAST:event_btnRevistaActionPerformed

    private void btnLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibroActionPerformed
        if (comunicacion.getIdioma().equals("ingles")) {
            jepLectura.setText(textoHtml.getOrgYPreEspañol());
            
        }
        if (comunicacion.getIdioma().equals("español")) {
            jepLectura.setText(textoHtml.getOrgYPreIngles());
        }
    }//GEN-LAST:event_btnLibroActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        comunicacion.setBPanel(true);
        comunicacion.cambio("Entretenimiento");
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLibro;
    private javax.swing.JButton btnRevista;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JEditorPane jepLectura;
    private javax.swing.JLabel lblLectura;
    private javax.swing.JLabel lblPrincipito;
    private javax.swing.JLabel lblRevista;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (comunicacion.getBPanel()) {
            this.setVisible(false);
            comunicacion.getVentanaInicioP().mostrarSubMenu(comunicacion.getPanel());
        }
        
        if (comunicacion.getIdioma().equals("ingles")) {
            lblRevista.setText("Pride and Prejudice");
            lblLectura.setText("Reading");
            lblPrincipito.setText("The Little Prince");
            jepLectura.setText("");
        }
        
        if (comunicacion.getIdioma().equals("español")) {
            lblLectura.setText("Lectura");
            lblRevista.setText("Orgullo y Prejuicio");
            lblPrincipito.setText("El Principito");
            jepLectura.setText("");
        }
    }
}
