/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vuelouy.interfaz.common;

import vuelouy.dominio.Viaje;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author alumnoFI
 */
public class MenuListaPedidos extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form MenuPedidos
     */
    private Viaje viaje;
    private ComunicacionPaneles comunicacion;

    /**
     *
     */
    public MenuListaPedidos() {
        initComponents();
    }

    /**
     *
     * @param v
     * @param com
     */
    public MenuListaPedidos(Viaje v, ComunicacionPaneles com) {
        viaje = v;
        comunicacion = com;
        comunicacion.addObserver(this);
        initComponents();
        actualizarLista();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstPedidos = new javax.swing.JList();
        btnPedidoRealizado = new javax.swing.JButton();

        lstPedidos.setBackground(new java.awt.Color(247, 247, 247));
        lstPedidos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "  Lista de Pedidos  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        lstPedidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lstPedidos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstPedidos);

        btnPedidoRealizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Check.png"))); // NOI18N
        btnPedidoRealizado.setToolTipText("");
        btnPedidoRealizado.setBorder(null);
        btnPedidoRealizado.setBorderPainted(false);
        btnPedidoRealizado.setContentAreaFilled(false);
        btnPedidoRealizado.setPreferredSize(new java.awt.Dimension(96, 96));
        btnPedidoRealizado.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/CheckP.png"))); // NOI18N
        btnPedidoRealizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoRealizadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(btnPedidoRealizado, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPedidoRealizado, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedidoRealizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoRealizadoActionPerformed
        if (lstPedidos.getSelectedIndex() >= 0) {
            viaje.pedidoRealizado(lstPedidos.getSelectedIndex());
            actualizarLista();
            if (viaje.getListaPedidos().isEmpty()) {
                comunicacion.getVentanaInicioT().notificar(false);
            }
        }
    }//GEN-LAST:event_btnPedidoRealizadoActionPerformed

    private void actualizarLista() {
     
            lstPedidos.setEnabled(true);
            lstPedidos.setListData(viaje.getListaPedidos().toArray());
            lstPedidos.setSelectedIndex(0);

        if (!viaje.getListaPedidos().isEmpty()) {
            comunicacion.getVentanaInicioT().notificar(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPedidoRealizado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstPedidos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        if (comunicacion.getPanel().equalsIgnoreCase(" ")) {
            actualizarLista();
        }
    }
}
