/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vuelouy.interfaz.common;

import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author alumnoFI
 */
public class MenuEntretenimiento extends javax.swing.JPanel implements Observer {

    private ComunicacionPaneles comunicacion;

    /**
     *
     */
    public MenuEntretenimiento() {
        initComponents();
    }

    /**
     *
     * @param p
     */
    public MenuEntretenimiento(ComunicacionPaneles p) {
        comunicacion = p;
        comunicacion.addObserver(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEntretenimiento = new javax.swing.JLabel();
        lblCamaraExterna = new javax.swing.JLabel();
        lblLectura = new javax.swing.JLabel();
        lblMusica = new javax.swing.JLabel();
        lblPintura = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnLectura = new javax.swing.JButton();
        bnCamarasExternas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnPintar = new javax.swing.JButton();
        btnMusica = new javax.swing.JButton();

        setEnabled(false);

        lblEntretenimiento.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblEntretenimiento.setText("Entretenimiento");

        lblCamaraExterna.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblCamaraExterna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCamaraExterna.setText("Cámaras");

        lblLectura.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblLectura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLectura.setText("Lectura");

        lblMusica.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMusica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMusica.setText("Música");

        lblPintura.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblPintura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPintura.setText("Pintura");

        btnLectura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Lectura.png"))); // NOI18N
        btnLectura.setBorder(null);
        btnLectura.setBorderPainted(false);
        btnLectura.setContentAreaFilled(false);
        btnLectura.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/LecturaP.png"))); // NOI18N
        btnLectura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturaActionPerformed(evt);
            }
        });

        bnCamarasExternas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Camaras.png"))); // NOI18N
        bnCamarasExternas.setBorder(null);
        bnCamarasExternas.setBorderPainted(false);
        bnCamarasExternas.setContentAreaFilled(false);
        bnCamarasExternas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/CamarasP.png"))); // NOI18N
        bnCamarasExternas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnCamarasExternasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnLectura, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215)
                .addComponent(bnCamarasExternas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLectura, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnCamarasExternas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        btnPintar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Pintar.png"))); // NOI18N
        btnPintar.setBorder(null);
        btnPintar.setBorderPainted(false);
        btnPintar.setContentAreaFilled(false);
        btnPintar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/PintarP.png"))); // NOI18N
        btnPintar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPintarActionPerformed(evt);
            }
        });

        btnMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Musica.png"))); // NOI18N
        btnMusica.setBorder(null);
        btnMusica.setBorderPainted(false);
        btnMusica.setContentAreaFilled(false);
        btnMusica.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/MusicaP.png"))); // NOI18N
        btnMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btnMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215)
                .addComponent(btnPintar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPintar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEntretenimiento))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLectura, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                                .addComponent(lblCamaraExterna, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPintura, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEntretenimiento)
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLectura)
                    .addComponent(lblCamaraExterna))
                .addGap(96, 96, 96)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMusica)
                    .addComponent(lblPintura))
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bnCamarasExternasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnCamarasExternasActionPerformed
        comunicacion.setBPanel(true);
        comunicacion.cambio("CamarasExternas");
    }//GEN-LAST:event_bnCamarasExternasActionPerformed

    private void btnMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicaActionPerformed
        comunicacion.setBPanel(true);
        comunicacion.cambio("Musica");
    }//GEN-LAST:event_btnMusicaActionPerformed

    private void btnLecturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturaActionPerformed
        comunicacion.setBPanel(true);
        comunicacion.cambio("Revista");
    }//GEN-LAST:event_btnLecturaActionPerformed

    private void btnPintarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPintarActionPerformed
        comunicacion.setBPanel(true);
        comunicacion.cambio("Pintura");
    }//GEN-LAST:event_btnPintarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnCamarasExternas;
    private javax.swing.JButton btnLectura;
    private javax.swing.JButton btnMusica;
    private javax.swing.JButton btnPintar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCamaraExterna;
    private javax.swing.JLabel lblEntretenimiento;
    private javax.swing.JLabel lblLectura;
    private javax.swing.JLabel lblMusica;
    private javax.swing.JLabel lblPintura;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (comunicacion.getBPanel()) {
            this.setVisible(false);
            comunicacion.getVentanaInicioP().mostrarSubMenu(comunicacion.getPanel());
            comunicacion.setBPanel(false);
        }
        
        
        if(comunicacion.getIdioma().equals("español")){
            lblMusica.setText("Música");
            lblCamaraExterna.setText("Cámaras");
            lblLectura.setText("Lectura");
            lblPintura.setText("Pintura");
            lblEntretenimiento.setText("Entretenimiento");
       }

        if(comunicacion.getIdioma().equals("ingles")){
            lblEntretenimiento.setText("Entretenimiento");
            lblMusica.setText("Music"); 
            lblCamaraExterna.setText("Cameras");
            lblLectura.setText("Reading");
            lblPintura.setText("Painting");
        }
        
        
    }
}
